default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  username: <%= ENV.fetch("DATABASE_USER") { "postgres" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE") { "gitscrapper_development" } %>

test:
  <<: *default
  database: gitscrapper_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DATABASE") { "gitscrapper_production" } %>
  cache:
    <<: *primary_production
    database: gitscrapper_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: gitscrapper_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: gitscrapper_production_cable
    migrations_paths: db/cable_migrate
